[build]
  command = "npm run build"
  publish = "production"
  functions = "production/netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/q/:campaign"
  to = "/.netlify/functions/qr?campaign=:campaign"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
